sudo: required

dist: trusty

language: generic

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

before_install:
  - sudo apt-get install -y -qq liblapack-dev
  - sudo apt-get install -y -qq libhdf5-dev
  - sudo apt-get install -y -qq python-dev
  - sudo apt-get install -y -qq python-opencv
  - sudo -H pip install -U pip setuptools

install:
  - sudo -H pip install -r requirements.txt
  - sudo python setup.py develop

script:
  - sudo -H pip install flake8 hacking
  - flake8 .
