sudo: false

dist: trusty

language: python

cache:
  - ccache
  - pip

matrix:
  include:
    - python: 2.7
    - python: 3.5

before_install:
  # install miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create --name=fcn python=$TRAVIS_PYTHON_VERSION -q -y
  - for req in $(cat requirements.txt); do
      if conda install --dry-run $req &>/dev/null; then
        conda install -q -y $req;
      else
        pip install -q $req;
      fi
    done
  - pip install .

before_script:
  - pip install -q hacking pytest

script:
  - flake8 .
  - pytest -vs tests

notifications:
  email: false
